### ISSUE TITLE
Markup glitch in tutorial docs

### ISSUE THREAD

**Issue by simonw** [radiac/nanodjango#15]
https://nanodjango.readthedocs.io/en/latest/tutorial.html

![CleanShot 2024-09-24 at 12 14 54@2x](https://github.com/user-attachments/assets/24b04fa3-8acd-4b4c-9bc8-e443b3fd5901)

**Comment by simonw** [comment]
Code: https://github.com/radiac/nanodjango/blob/455a0dd36c026f08716987912a8610cc8d90dd34/docs/tutorial.rst#L61-L72

I think it's the double colon.

**Comment by simonw** [comment]
Spotted these errors running `make html`:

```
/private/tmp/nanodjango/docs/index.rst:10: WARNING: toctree contains reference to nonexisting document 'api'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /private/tmp/nanodjango/docs/apis.rst: WARNING: document isn't included in any toctree
```

**Comment by radiac** [comment]
Thanks for sorting! I was too fat with my fix!
