### ISSUE TITLE
AttributeError running via uv run

### ISSUE THREAD

**Issue by brunns** [radiac/nanodjango#21]
Almost certainly an error on my side, but I can't see it. My script looks like this:

```python
# /// script
# dependencies = ["nanodjango"]
# ///

from nanodjango import Django

app = Django()

@app.route("/")
def hello(request):
    return "Hello World!"

if __name__ == "__main__":
    app.run()
```

Running it with uv (version 0.4.16) I get:

```shell
$ uv run nd_hello.py
Reading inline script metadata from: nd_hello.py
Traceback (most recent call last):
  File "/Users/brunns/temp/nd_hello.py", line 14, in <module>
    app.run()
  File "/Users/brunns/.cache/uv/archive-v0/rtJTHAUnOiRDZKIBA0bwC/lib/python3.12/site-packages/nanodjango/app.py", line 372, in run
    self._prepare(is_prod=False)
  File "/Users/brunns/.cache/uv/archive-v0/rtJTHAUnOiRDZKIBA0bwC/lib/python3.12/site-packages/nanodjango/app.py", line 295, in _prepare
    or getattr(sys.modules["__main__"], self._instance_name) != self
                                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Django' object has no attribute '_instance_name'
```

**Comment by xdrdak** [comment]
It appears you are attempting to run the app via `uv run nd_hello.py`.

However, as per the docs, you need to invoke `nanodjango run` instead.

Assuming you are in a uv initialized project,  you can use `uv run nanodjango run nd_hello.py`.

Otherwise: `uvx nanodjango run nd_hello.py` would work as well.

**Comment by radiac** [comment]
Thanks for spotting this! You should be able to `uv run nd_hello.py`, but there is a problem - it must have crept into a recent release, and there's a glaring lack of tests around this!

I'll be taking a look at it in the DjangoCon sprints over the next couple of days.

**Comment by brunns** [comment]
Thanks @radiac!
