### ISSUE TITLE
AttributeError: 'Django' object has no attribute '_instance_name' when running as a standalone Python script directly

### ISSUE THREAD

**Issue by j0hnc** [radiac/nanodjango#22]
Hi, great project I love it!

Unfortunately, I am unable to get nanodjango running as a standalone script.

The [documentation](https://nanodjango.readthedocs.io/en/latest/usage.html#running-your-script-directly) says:

> You don’t need to use the nanodjango command - you can call app.run() from the bottom of your script, eg:

```python
from nanodjango import Django
app = Django()
...
if __name__ == "__main__":
    app.run()
```

Copying this code into a file, however, gives me the following error:

```
% python3 app.py
Traceback (most recent call last):
  File "/Users/j0hnc/etc/code/python/django/nanodjango/app.py", line 5, in <module>
    app.run()
  File "/Users/j0hnc/etc/code/python/django/nanodjango/.venv/lib/python3.12/site-packages/nanodjango/app.py", line 372, in run
    self._prepare(is_prod=False)
  File "/Users/j0hnc/etc/code/python/django/nanodjango/.venv/lib/python3.12/site-packages/nanodjango/app.py", line 295, in _prepare
    or getattr(sys.modules["__main__"], self._instance_name) != self
                                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Django' object has no attribute '_instance_name'
```

Unsurprisingly, I get the same error when I try to use pipx via `pipx run app.py` on the code from the [documentation](https://nanodjango.readthedocs.io/en/latest/usage.html#running-it-as-a-standalone-script):

```python
# /// script
# dependencies = ["nanodjango"]
# ///
from nanodjango import Django
app = Django()
...
if __name__ == "__main__":
    app.run()
```

**Comment by it-is-wednesday** [comment]
https://github.com/radiac/nanodjango/issues/21

**Comment by radiac** [comment]
Thanks for reporting this! This looks like the same underlying issue as #21, should be fixed in the next release.
