### ISSUE TITLE
Lower effort initial setup

### ISSUE THREAD

**Issue by SmileyChris** [radiac/nanodjango#4]
Currently you've got these initial instructions:

1. `nanodjango counter.py run makemigrations counter`
2. `nanodjango counter.py run migrate`
3. `nanodjango counter.py run createsuperuser`
4. `nanodjango counter.py run`

It seems that `run` could just do all of these steps conditionally!

If any models are declared:
> Step 1, easy enough to check for an migration folder, and run automatically
>  Step 2, potentially you should migrate at the start of every run

if admin is used, or any models reference `User`:
>  Step 3, automatically run this if empty users table

**Comment by radiac** [comment]
I really like this idea! makemigrations does nothing if the models haven't changed, so it should be safe to run every time (albeit a slightly slower startup).

Could have it makemigrations and migrate when run in wsgi mode too (although probably not createsuperuser there?)

**Comment by radiac** [comment]
I liked the idea but worried about the edge cases and unpredictable side effects, so put it in a new `start` command.
